import { DemoStep } from "../DemoTour";

export const productCardDemoSteps: DemoStep[] = [
  {
    id: "price-per-unit",
    targetSelector: "[data-demo='price-per-unit']",
    action: "point",
    tooltip: "💰 Цена за 1 кг или 1 шт — удобно сравнивать товары",
    tooltipPosition: "bottom",
    duration: 3000,
  },
  {
    id: "product-name",
    targetSelector: "[data-demo='product-name']",
    action: "tap",
    tooltip: "📝 Нажмите на название для описания товара",
    tooltipPosition: "bottom",
    duration: 3500,
  },
  {
    id: "product-image",
    targetSelector: "[data-demo='product-image']",
    action: "tap",
    tooltip: "🖼️ Нажмите на фото для просмотра всех изображений",
    tooltipPosition: "bottom",
    duration: 3500,
  },
  {
    id: "buy-full",
    targetSelector: "[data-demo='buy-full']",
    action: "tap",
    tooltip: "📦 ЦЕЛАЯ упаковка — нажмите чтобы добавить в корзину",
    tooltipPosition: "top",
    duration: 4000,
  },
  {
    id: "buy-half",
    targetSelector: "[data-demo='buy-half']",
    action: "point",
    tooltip: "½ ПОЛОВИНА упаковки — если целая слишком большая",
    tooltipPosition: "top",
    duration: 3500,
  },
  {
    id: "cart-button",
    targetSelector: "[data-demo='cart-button']",
    action: "tap",
    tooltip: "🛒 Ваша корзина — нажмите для просмотра и оформления",
    tooltipPosition: "bottom",
    duration: 3500,
  },
  {
    id: "checkout-info",
    targetSelector: "[data-demo='checkout-button']",
    action: "tap",
    tooltip: "✅ Оформить заказ — укажите адрес доставки",
    tooltipPosition: "top",
    duration: 3500,
  },
];

// Demo product data
export const DEMO_PRODUCT = {
  id: "demo-product-001",
  name: "🎓 Демо — Сыр Пармезан",
  description: "Это демонстрационный товар для обучения. Выдержка 24 месяца, насыщенный вкус с кристалликами. После завершения демо товар исчезнет.",
  price: 1500,
  unit: "кг",
  unit_weight: 2.5,
  images: [
    "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop",
    "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=400&h=400&fit=crop",
  ],
  quantity: 100,
  sku: "DEMO-001",
  slug: "demo-parmesan",
  catalog_status: "in_stock" as const,
  catalog_portion_prices: {
    full: 1500,
    half: 1600,
    quarter: 1700,
  },
  catalog_categories: [] as string[],
  packaging_type: "head",
  compare_price: null,
  catalog_markup_type: null,
  catalog_markup_value: null,
  price_full: null,
  price_half: null,
  price_quarter: null,
  price_portion: null,
  portion_weight: null,
};
